### ISSUE TITLE
Feeder

### ISSUE THREAD

**Issue by Muirrum** [AndromedaOne/2020Code#32]
![statemachinefeeder](https://user-images.githubusercontent.com/8702646/73501825-0f0e3980-4395-11ea-8c1f-a2c936b8909d.jpg)

Using this state machine, run the feeder autonomously in conjunction with the intake and shooter.

**Comment by Dev-Osmium** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?927E826A4F02FEE92A78DD5FABA8E9951E9D

**Comment by Dev-Osmium** [comment]
Update: Have finished code, need to test with hardware
